name: ChatEmojis
version: ${project.version}
main: com.vomarek.ChatEmojis
softdepend: [PlaceholderAPI]
authors: [1vomarek1]
website: vomarek.com
commands:
  chatemojis:
    description: Command to reload Emojis menu
    usage: "Usage: /<command> reload"
permissions:
  chatemojis.admin:
    description: Administrator permissions for ChatEmojis
    default: op
    children:
      chatemojis.reload: true
      chatemojis.emoji.*: true
  chatemojis.manage:
    description: Permission to manage emojis
    default: op
  chatemojis.reload:
    description: Permission to reload ChatEmojis
    default: op
  chatemojis.emoji.*:
    description: Permission to use all emojis
    default: op