#  ░█████╗░██╗░░██╗░█████╗░████████╗███████╗███╗░░░███╗░█████╗░░░░░░██╗██╗░██████╗░██████╗░██╗░░░██╗██╗
#  ██╔══██╗██║░░██║██╔══██╗╚══██╔══╝██╔════╝████╗░████║██╔══██╗░░░░░██║██║██╔════╝██╔════╝░██║░░░██║██║
#  ██║░░╚═╝███████║███████║░░░██║░░░█████╗░░██╔████╔██║██║░░██║░░░░░██║██║╚█████╗░██║░░██╗░██║░░░██║██║
#  ██║░░██╗██╔══██║██╔══██║░░░██║░░░██╔══╝░░██║╚██╔╝██║██║░░██║██╗░░██║██║░╚═══██╗██║░░╚██╗██║░░░██║██║
#  ╚█████╔╝██║░░██║██║░░██║░░░██║░░░███████╗██║░╚═╝░██║╚█████╔╝╚█████╔╝██║██████╔╝╚██████╔╝╚██████╔╝██║
#  ░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝░╚════╝░░╚════╝░╚═╝╚═════╝░░╚═════╝░░╚═════╝░╚═╝
#
# ChatEmojisGUI is plugin that allows you to replace specific text in chat message with something different.
# Such as (╯°□°）╯︵ ┻━┻. Everything here can be also edited from ingame using command /emojis.
#
# 
############################################################
# +------------------------------------------------------+ #
# |                   Configuration                      | #
# +------------------------------------------------------+ #
############################################################
#
# If you don't know how to configure ChatEmojisGUI you should use ingame configuration (/emojis).
# ChatEmojisGUI's configuration structure is:
# 
# └┐
#  ├ Emojis
#  └┐
#   ├ Emoji - tableflip (Emoji can be replaced with anything. | It is your emoji ID & name)
#   └┐
#    ├ identifier: - :tableflip: (Identifier of your emoji | What will be replaced in chat)
#    └ emoji: - :(╯°□°）╯︵ ┻━┻: (Emoji | What will your emoji look like)
#
############################################################
# +------------------------------------------------------+ #
# |                  Having troubles?                    | #
# +------------------------------------------------------+ #
############################################################
#
# Are you having troubles setting ChatEmojisGUI up? Join my support Discord server using this link:
# https://discord.gg/UjQJW5Z
# 
############################################################
# +------------------------------------------------------+ #
# |            Plugin created by 1vomarek1               | #
# +------------------------------------------------------+ #
############################################################
# ChatEmojisGUI v0.1 [BETA]
#
#
#
Emojis:
   tableflip:
      identifier: ":tableflip:"
      emoji: "(╯°□°）╯︵ ┻━┻"
   correct:
      identifier: ":correct:"
      emoji: "✔"
   incorrect:
      identifier: ":incorrect:"
      emoji: "✖"
   shrug:
      identifier: ":shrug:"
      emoji: "¯\_(ツ)_/¯"
   cry:
      identifier: ":cry:"
      emoji: "ಥ_ಥ"
   hug:
      identifier: ":hug:"
      emoji: "(づ￣ ³￣)づ"
   kiss:
      identifier: ":kiss:"
      emoji: "( ˘ ³˘)♥ "
   heart:
      identifier: "<3"
      emoji: "❤"
   rage:
      identifier: ":rage:"
      emoji: "(ノಠ益ಠ)ノ彡┻━┻"