name: ChatEmojisGUI
description: Ultimate emojis plugin
version: 0.1 [BETA]
main: com.vomarek.ChatEmojisGUI.ChatEmojisGUI
api-version: 1.12.2
commands:
   emojis:
      description: Command to open Emojis menu
      